name: portfolio_projects

packages:
  - apps/*
  - packages/*

command:
  version:
    branch: main
    hooks:
      preCommit: melos run update-apps-build-number

scripts:
  update-apps-build-number:
    description: Increase the build number of all Flutter packages that is updated
    packageFilters:
      flutter: true

    # Make sure to use the python executable from the virtual environment
    # .\ci\.venv\Scripts\activate
    steps:
      - python ci/global/upd_apps_build_num.py
      - git add *build_info.yaml *pubspec.yaml
