# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

import 'utils.rb'

# This is the configuration for the Android platform
default_platform(:android)

# Error handling
error do |lane, exception|
  UI.error get_package_name()
  UI.error "Error in lane #{lane}:"
  UI.error exception.message

  if ENV.include?('GITHUB_ENV')
    sh("echo EXCEPTION=#{exception.message} >> $GITHUB_ENV")
  end
end

platform :android do
  desc "Submit current bundle to the internal track in the Google Play"
  lane :deploy_internal do |options|
    publish = get_publish_par(options)

    # Deploy the current bundle to the internal track in the Google Play.
    upload_to_play_store(
        validate_only: !publish,
        track: 'internal',
        # release_status: 'draft',
        skip_upload_metadata: true,
        sync_image_upload: true,
        changes_not_sent_for_review: true,
        aab: '../build/app/outputs/bundle/prodRelease/app-prod-release.aab',
        mapping_paths: [
          '../build/app/intermediates/merged_native_libs/prodRelease/out/lib/native-debug-symbols.zip',
          '../build/app/outputs/mapping/prodRelease/mapping.txt'
        ],
    )
  end
end
