targets:
  $default:
    builders:
      dart_mappable_builder:
        generate_for:
          include:
            - 'lib/**/domain/**.dart'
        options:
          renameMethods:
            fromJson: fromJsonString
            toJson: toJsonString
            fromMap: fromJson
            toMap: toJson

      auto_route_generator:
        generate_for:
          include:
            - 'lib/routing/**.dart'
            - 'lib/**/presentation/**.dart'

      riverpod_generator:
        generate_for:
          include:
            - 'lib/**/**_repository.dart'
            - 'lib/**/**_source.dart'
            - 'lib/**/**_service.dart'
            - 'lib/**/**_provider.dart'
            - 'lib/**/**_providers.dart'
            - 'lib/**/**_controller.dart'

      drift_dev:
        enabled: false

      drift_dev:analyzer:
        enabled: true
        generate_for: &drift_dev_modular_generate_for
          include:
            - 'lib/backend/database/**.dart'
            - 'lib/**/drift_tables/**.dart'
            - 'lib/**/**_database.dart'

      drift_dev:modular:
        enabled: true
        generate_for: *drift_dev_modular_generate_for
#
# global_options:
#   drift_dev:
#     runs_before:
#       - riverpod_generator:riverpod_generator
