targets:
  $default:
    builders:
      dart_mappable_builder:
        generate_for:
          include:
            - 'lib/**/domain/**.dart'
        options:
          renameMethods:
            fromJson: fromJsonString
            toJson: toJsonString
            fromMap: fromJson
            toMap: toJson

      drift_dev:
        generate_for:
          include:
            - 'lib/backend/database/**.dart'
            - 'lib/**/drift_tables/**.dart'

      riverpod_generator:
        generate_for:
          include:
            - 'lib/**/**_repository.dart'
            - 'lib/**/**_service.dart'
            - 'lib/**/**_provider.dart'
            - 'lib/**/**_providers.dart'
            - 'lib/**/**_controller.dart'

      auto_route_generator:
        generate_for:
          include:
            - 'lib/routing/**.dart'
            - 'lib/**/presentation/**.dart'
