targets:
  $default:
    builders:
      freezed:
        generate_for:
          include:
            - 'lib/features/**/domain/**.dart'

      json_serializable:
        generate_for:
          include:
            - 'lib/features/**/domain/**.dart'

      riverpod_generator:
        generate_for:
          include:
            - 'lib/exceptions/**.dart'
            # - 'lib/features/**/data/**_repository.dart'
            # - 'lib/features/**/application/**_service.dart'
            # - 'lib/features/**/presentation/**_screen.dart'
            - 'lib/features/**.dart'
            - 'lib/routing/**.dart'

      auto_route_generator:
        generate_for:
          include:
            - 'lib/features/**/presentation/**_screen.dart'
            - 'lib/routing/**.dart'
