targets:
  $default:
    builders:
      freezed:
        generate_for:
          include:
            - 'lib/features/**/domain/**.dart'

      json_serializable:
        options:
          explicit_to_json: true

        generate_for:
          include:
            - 'lib/features/**/domain/**.dart'

      riverpod_generator:
        generate_for:
          include:
            - 'lib/exceptions/**.dart'
            - 'lib/features/**/**_repository.dart'
            - 'lib/features/**/**_service.dart'
            - 'lib/features/**/**_provider.dart'
            - 'lib/features/**/**_providers.dart'
            - 'lib/features/**/**_controller.dart'
            - 'lib/routing/**.dart'

      auto_route_generator:
        generate_for:
          include:
            - '**_screen.dart'
            - 'lib/routing/**.dart'
