targets:
  $default:
    builders:
      freezed:
        generate_for:
          include:
            - 'lib/features/**/domain/**.dart'

      json_serializable:
        options:
          explicit_to_json: true

        generate_for:
          include:
            - 'lib/features/**/domain/**.dart'

      riverpod_generator:
        generate_for:
          include:
            - 'lib/exceptions/**.dart'
            - 'lib/routing/**.dart'
            - 'lib/**/**_repository.dart'
            - 'lib/**/**_service.dart'
            - 'lib/**/**_provider.dart'
            - 'lib/**/**_providers.dart'
            - 'lib/**/**_controller.dart'

      auto_route_generator:
        generate_for:
          include:
            - '**_screen.dart'
            - 'lib/routing/**.dart'
