targets:
  $default:
    builders:
      dart_mappable_builder:
        generate_for:
          include:
            - 'lib/**/domain/**.dart'
        options:
          renameMethods:
            fromJson: fromJsonString
            toJson: toJsonString
            fromMap: fromJson
            toMap: toJson

      riverpod_generator:
        generate_for:
          include:
            - 'lib/backend/**.dart'
            - 'lib/exceptions/**.dart'
            - 'lib/routing/**.dart'
            - 'lib/logging/**.dart'
            - 'lib/**/**_repository.dart'
            - 'lib/**/**_service.dart'
            - 'lib/**/**_provider.dart'
            - 'lib/**/**_providers.dart'
            - 'lib/**/**_controller.dart'

      auto_route_generator:
        generate_for:
          include:
            - 'lib/routing/**.dart'
            - '**_screen.dart'
